spring:
  profiles:
    active: dev
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: localhost:48848
      config:
        namespace: ${spring.profiles.active:dev}
      discovery:
        namespace: ${spring.profiles.active:dev}
    sentinel:
      transport:
        dashboard: 48858
      datasource:
        # 数据源名称（自定义，如 flow-rule 表示限流规则）
        flow-rule:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            data-id: ${spring.application.name}-flow-rules # 规则存储的 dataId（建议包含应用名，避免冲突）
            group-id: SENTINEL_GROUP # 分组（自定义，建议统一用 SENTINEL_GROUP）
            rule-type: flow # 规则类型：flow（限流）、degrade（熔断）、param-flow（热点参数）等
            # 可选：Nacos 认证信息（若开启了鉴权）
            username: nacos
            password: Asdfgh1235.
        # 如需配置熔断规则，新增一个数据源
        degrade-rule:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
            rule-type: degrade
            username: nacos
            password: Asdfgh1235.
--- #多文档模式dev环境价值配置
spring:
  config:
    import:
      - nacos:common.yml?group=order
      - nacos:database.yml?group=order
    activate:
      on-profile: dev
logging:
  level:
    com.zotci.order.feign: debug
--- #多文档模式test环境价值配置
spring:
  config:
    import:
      - nacos:common.yml?group=order
      - nacos:database.yml?group=order
    activate:
      on-profile: test
---

server:
  port: 8001

springdoc:
  swagger-ui:
    path: /api/docs