spring:
  profiles:
    active: dev
    include: route
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:48848
      discovery:
        namespace: ${spring.profiles.active:dev}
server:
  port: 80