spring:
  application:
    name: service-product
  cloud:
    nacos:
      server-addr: localhost:48848
      config:
        import-check:
          enabled: false  #禁用导入检查
        namespace: ${spring.profiles.active:dev}
      discovery:
        namespace: ${spring.profiles.active:dev}
    sentinel:
      transport:
        dashboard: localhost:48858
      eager: true
server:
  port: 9001
springdoc:
  swagger-ui:
    path: /api/docs